version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - '8000:8000'
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - postgres:postgres
    env_file: .env
    environment:
      DEBUG: 'true'

  postgres:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
